export enum DStereotype {
  PROJECT = "project",
  APPLICATION = "application",
  MODULE = "module",
  SERVICE = "service",
  BEHAVIOR = "behavior",
  ENTITY = "entity",
  POLICY = "policy",
  MIDDLEWARE = "middleware",
  INDEX = "index",
  DAMBA = "damba",
  CONFIG = "config",
  EXTRA = "extra",
  EXTRA_HOOK = "extra_hook",
  VALIDATOR = "validator",
}
