#!/usr/bin/env node
import { Command } from "commander";
import fs from "node:fs";
import path from "node:path";

const program = new Command();

/** Convert a string to PascalCase */
function toPascalCase(s: string): string {
  return s
    .trim()
    .replace(/[_-\s]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Ensure directory exists */
function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

/** Create a file if not exists */
function ensureFile(filePath: string, contents = "") {
  if (!fs.existsSync(filePath)) fs.writeFileSync(filePath, contents, "utf8");
}

/** Build index.ts contents */
function buildIndexTs() {
  return `// Auto-generated by Damba CLI
export * from "./middlewares";
export * from "./policies";
export * from "./behaviors";
`;
}

/** Create one service scaffold in CWD */
function createOne(nameRaw: string) {
  const cwd = process.cwd();
  const name = toPascalCase(nameRaw);
  const root = path.join(cwd, name);

  const middlewaresDir = path.join(root, "middlewares");
  const policiesDir = path.join(root, "policies");
  const behaviorsDir = path.join(root, "behaviors");
  const entitiesDir = path.join(root, "entities");
  const indexFile = path.join(root, "index.ts");

  ensureDir(root);
  ensureDir(middlewaresDir);
  ensureDir(policiesDir);
  ensureDir(behaviorsDir);
  ensureDir(entitiesDir);
  ensureFile(indexFile, buildIndexTs());

  // Optional: create barrel files inside subfolders so exports work immediately
  ensureFile(path.join(middlewaresDir, "index.ts"), "// middlewares barrel\n");
  ensureFile(path.join(policiesDir, "index.ts"), "// policies barrel\n");
  ensureFile(path.join(behaviorsDir, "index.ts"), "// behaviors barrel\n");

  console.log(`✔ ${name}/ created`);
}

/** Create many service scaffolds in CWD */
async function createMany(names: string[]) {
  if (!names.length) {
    console.error("Provide at least one name. Example: dam create service Employee role user");
    process.exit(1);
  }
  names.forEach(createOne);
  console.log("Done.");
}

program.name("dam").description("Damba CLI").version("1.0.0");

program
  .command("create")
  .description("Create scaffolds in the current directory")
  .argument("<section>", "service | services")
  .argument("<names...>", "one or more names, e.g. Employee role user")
  .action(async (section, names: string[]) => {
    const s = String(section).toLowerCase();
    if (s !== "service" && s !== "services") {
      console.error(`Unknown section: ${section}. Use "service" or "services".`);
      process.exit(1);
    }
    await createMany(names);
  });

// Also allow: dam create <names...>  (no section)
program
  .command("create-here")
  .description("Alias: create directly without a section")
  .argument("<names...>")
  .action(async (names: string[]) => createMany(names));

program.parse(process.argv);
