/* eslint-disable @typescript-eslint/no-explicit-any */
import { DambaRepository } from '@Damba/v2/dao';
import { DStereotype } from '@Damba/v2/model/DStereotype';
import { AppServices } from '@Database/entities/AppServices';
import { Application } from '@Database/entities/Application';
import { BehaviorChain } from '@Database/entities/Behaviors/BehaviorChain';
import { Modules } from '@Database/entities/Modules';
import { Project } from '@Database/entities/Project';
import { DataSource } from 'typeorm';
import { saveCodeFile, baseMeta } from './helpers';

/**
 * Generates the service file that uses Damba's default CRUD system.
 * No LLM needed — behaviors are empty, CRUD is auto-generated from the entity.
 */
const generateServiceWithCrud = (svc: AppServices, mod: Modules): string => {
  const entityName = svc.defaultEntity ?? svc.name;
  const servicePath = `/${mod.name?.toLowerCase()}/${svc.name?.toLowerCase()}`;
  const svcName = (svc.name ?? 'service').replace(/[^a-zA-Z0-9]/g, '');

  return `import { createDambaService, DambaService, BehaviorsChainLooper } from '@Damba/v2/service/DambaService';
import { ${entityName} } from '@Database/entities/${mod.name}/${entityName}';

const service: DambaService = {
  name: '${servicePath}',
  entity: ${entityName},
};

// Default CRUD is auto-generated by Damba from the entity.
// Add custom BehaviorHooks here as needed.
const behaviors: BehaviorsChainLooper = {};

export default createDambaService({ service, behaviors });
`;
};

/**
 * Saves a BehaviorChain for each service (no LLM call).
 * The API uses Damba's default CRUD system — behaviors are empty shells
 * that can be customized later by the user.
 */
export const saveBehaviorsForService = async (
  svc: AppServices,
  mod: Modules,
  app: Application,
  project: Project,
  dao: DambaRepository<DataSource>,
): Promise<BehaviorChain> => {
  const meta = {
    orgId: (project as any).organization?.id,
    projId: project.id,
    appId: app.id,
    moduleId: mod.id,
    servId: svc.id,
    created_by: project.created_by,
    environment: mod.environment,
  };

  // Create the BehaviorChain (one per service)
  const chain = (await dao.DSave(BehaviorChain, {
    name: `${svc.name}Behaviors`,
    description: `Behavior chain for ${svc.name} — uses default Damba CRUD`,
    appService: svc,
    ...meta,
  } as Partial<BehaviorChain>)) as BehaviorChain;

  // Generate service file with default CRUD
  const svcName = (svc.name ?? 'service').replace(/[^a-zA-Z0-9]/g, '');
  const content = generateServiceWithCrud(svc, mod);
  await saveCodeFile(dao, {
    name: `${svcName}.ts`,
    path: `/src/modules/${mod.name}/services`,
    fileExtension: 'ts',
    data: { content },
    stereotype: DStereotype.BEHAVIOR,
    moduleId: mod.id,
    serviceId: svc.id,
    ...baseMeta(app, project, mod.environment),
  });

  return chain;
};
